# Generated by Django 4.2.6 on 2024-01-26 13:28

import ClinicApp.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_enumfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('ClinicApp', '0002_department_employee_user_address_user_birthdate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('employee_info', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='doctor_info', serialize=False, to='ClinicApp.employee')),
                ('departments', models.ManyToManyField(related_name='doctors', to='ClinicApp.department')),
            ],
        ),
        migrations.CreateModel(
            name='HealthRecord',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('updated_date', models.DateField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('symstoms', models.TextField()),
                ('paid', models.BooleanField(default=False)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_records', to='ClinicApp.doctor')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('updated_date', models.DateField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('image', models.ImageField(upload_to='medicines/%Y/%m')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Nurse',
            fields=[
                ('employee_info', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='nurse_info', serialize=False, to='ClinicApp.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('user_info', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='patient_info', serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('updated_date', models.DateField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='employee',
            name='user_info',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='employee_info', serialize=False, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='MedicinePrice',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('updated_date', models.DateField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('unit', django_enumfield.db.fields.EnumField(default=2, enum=ClinicApp.models.Unit)),
                ('unit_price', models.IntegerField()),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='ClinicApp.medicine')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MedicineDetails',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('updated_date', models.DateField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('amount', models.FloatField()),
                ('unit', django_enumfield.db.fields.EnumField(default=0, enum=ClinicApp.models.Unit)),
                ('health_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ClinicApp.healthrecord')),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ClinicApp.medicine')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='medicine',
            name='vendor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medicines', to='ClinicApp.vendor'),
        ),
        migrations.CreateModel(
            name='Instruction',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('updated_date', models.DateField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('amount', models.FloatField()),
                ('unit', django_enumfield.db.fields.EnumField(default=0, enum=ClinicApp.models.Unit)),
                ('period', django_enumfield.db.fields.EnumField(default=0, enum=ClinicApp.models.Period)),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ClinicApp.medicinedetails')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='healthrecord',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_records', to='ClinicApp.patient'),
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('updated_date', models.DateField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('ExpectedDate', models.DateTimeField()),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='ClinicApp.department')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='ClinicApp.patient')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Confirmation',
            fields=[
                ('appointment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='confirmation', serialize=False, to='ClinicApp.appointment')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('nurse', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmation', to='ClinicApp.nurse')),
            ],
        ),
    ]
