# Generated by Django 4.2.6 on 2024-02-07 18:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClinicApp', '0003_receiptdetail_receipt_alter_appointment_expecteddate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='ExpectedDate',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 7, 18, 45, 41, 728521)),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='created_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
