# Generated by Django 4.2.6 on 2024-01-26 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClinicApp', '0003_doctor_healthrecord_medicine_nurse_patient_vendor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthrecord',
            name='medicines',
            field=models.ManyToManyField(related_name='records', through='ClinicApp.MedicineDetails', to='ClinicApp.medicine'),
        ),
    ]
