# Generated by Django 4.2.6 on 2024-02-07 18:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClinicApp', '0004_alter_appointment_expecteddate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='ExpectedDate',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 7, 18, 46, 17, 403488)),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='created_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
