# Generated by Django 4.2.6 on 2024-01-29 03:38

import ClinicApp.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_enumfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('ClinicApp', '0005_alter_appointment_id_alter_department_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='employee_info',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='doctor_info', serialize=False, to='ClinicApp.employee'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='user_info',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='employee', serialize=False, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=django_enumfield.db.fields.EnumField(default=2, enum=ClinicApp.models.UserRole),
        ),
    ]
