# Generated by Django 4.2.6 on 2024-02-09 17:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClinicApp', '0006_alter_appointment_expecteddate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='ExpectedDate',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 9, 17, 28, 35, 587900)),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='created_date',
            field=models.DateField(auto_now_add=True, default='2024-02-09'),
            preserve_default=False,
        ),
    ]
