# Generated by Django 4.2.6 on 2024-01-29 03:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ClinicApp', '0006_alter_doctor_employee_info_alter_employee_user_info_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='confirmation',
            name='appointment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='confirmation', serialize=False, to='ClinicApp.appointment'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='user_info',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='patient_info', serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
