# Generated by Django 4.2.6 on 2024-01-29 13:03

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ClinicApp', '0008_alter_nurse_employee_info'),
    ]

    operations = [
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('total', models.IntegerField()),
                ('created_date', models.DateTimeField(default=datetime.datetime(2024, 1, 29, 20, 2, 56, 381834))),
                ('paid', models.BooleanField(default=False)),
                ('nurse', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receipt_confirmed', to='ClinicApp.nurse')),
                ('record', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='receipt', to='ClinicApp.healthrecord')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('updated_date', models.DateField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='medicinedetails',
            name='total',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='confirmation',
            name='nurse',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointment_confirmed', to='ClinicApp.nurse'),
        ),
        migrations.CreateModel(
            name='ReceiptDetail',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('price', models.IntegerField(default=0)),
                ('receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detail', to='ClinicApp.receipt')),
            ],
        ),
        migrations.AddField(
            model_name='healthrecord',
            name='services',
            field=models.ManyToManyField(related_name='records', to='ClinicApp.service'),
        ),
    ]
