# Generated by Django 4.2.6 on 2024-02-11 14:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClinicApp', '0009_alter_appointment_expecteddate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthrecord',
            name='overview',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='ExpectedDate',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 11, 14, 19, 27, 456844)),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='created_date',
            field=models.DateField(default=datetime.date(2024, 2, 11)),
        ),
    ]
