# Generated by Django 4.2.6 on 2024-01-31 07:05

import cloudinary.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClinicApp', '0010_alter_employee_diploma_alter_medicine_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 31, 14, 5, 17, 661061)),
        ),
    ]
