# Generated by Django 4.2.6 on 2024-02-01 09:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClinicApp', '0012_remove_doctor_departments_alter_receipt_created_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='comfirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='ExpectedDate',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 1, 16, 17, 39, 981060)),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 1, 16, 17, 39, 983053)),
        ),
    ]
