# Generated by Django 4.2.6 on 2024-02-01 17:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClinicApp', '0014_alter_appointment_expecteddate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='ExpectedDate',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 1, 17, 59, 35, 637783)),
        ),
    ]
