# Generated by Django 4.2.6 on 2024-02-01 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClinicApp', '0015_alter_appointment_expecteddate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='ExpectedDate',
            field=models.DateTimeField(default='02/01/2024, 18:08'),
        ),
        migrations.AlterUniqueTogether(
            name='appointment',
            unique_together={('patient', 'ExpectedDate')},
        ),
    ]
