# Generated by Django 4.2.6 on 2024-02-01 18:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClinicApp', '0016_alter_appointment_expecteddate_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='comfirmed',
            new_name='confirmed',
        ),
        migrations.AlterField(
            model_name='appointment',
            name='ExpectedDate',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 1, 18, 53, 38, 580987)),
        ),
    ]
