# Generated by Django 4.2.6 on 2024-02-03 09:33

import cloudinary.models
import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ClinicApp', '0017_rename_comfirmed_appointment_confirmed_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instruction',
            name='medicine',
        ),
        migrations.AddField(
            model_name='medicinedetails',
            name='instructions',
            field=models.ManyToManyField(related_name='medicine', to='ClinicApp.instruction'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='ExpectedDate',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 3, 9, 33, 5, 597855)),
        ),
        migrations.AlterField(
            model_name='medicinedetails',
            name='health_record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicines_detail', to='ClinicApp.healthrecord'),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
    ]
