# Generated by Django 4.2.6 on 2024-02-03 10:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClinicApp', '0018_remove_instruction_medicine_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='healthrecord',
            old_name='paid',
            new_name='locked',
        ),
        migrations.AlterField(
            model_name='appointment',
            name='ExpectedDate',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 3, 10, 15, 29, 101102)),
        ),
    ]
