# Generated by Django 4.2.6 on 2024-02-04 21:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClinicApp', '0019_rename_paid_healthrecord_locked_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='ExpectedDate',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 4, 21, 56, 26, 901040)),
        ),
        migrations.AlterUniqueTogether(
            name='medicinedetails',
            unique_together={('health_record', 'medicine')},
        ),
    ]
